include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/oci-publish@8
    inputs:
      licenses: AGPL-3.0-or-later
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
