variables:
  GIT_DEPTH: 0
  CI_DOCKERHUB_IMAGE: huncrys/minio-console
  CI_GHCR_IMAGE: huncrys/minio-console

stages:
  - build
  - deploy
  - release

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/oci-publish@8
    inputs:
      licenses: AGPL-3.0-or-later
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
      args:
        - CI_COMMIT_TAG=$CI_COMMIT_TAG
